
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentiment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ineuronchallnge
  template:
    metadata:
      labels:
        app: ineuronchallnge
    spec:
      containers:
      - name: automlops-app
        image: gcr.io/ineuronchallenge/flaskapp:v1
        ports:
        - containerPort: 5000

